'use strict';
// Gates for the Labs page's forward-test record.
//
// WHY THIS EXISTS. Seven profit factors (2.71, 2.35, 4.08, 1.24, 1.93,
// 1.20, 1.05) were each quoted here as the baseline and each withdrawn,
// and every withdrawal moved the number down. The backend now writes an
// immutable weekly record precisely so the eighth cannot happen -- but a
// record only helps if the PAGE makes it hard to lift a number out of its
// context. These assert the consequence of getting the rendering wrong:
//
//   1. a refused verdict rendered as a number, or as a blank, is read as a
//      result -- which is exactly how a 3-trade sample funds a strategy;
//   2. three mechanisms pooled into one figure is a number about nothing,
//      and it is the flattering one;
//   3. a figure shown without its mechanism status and the not-a-backtest
//      warning is a figure that will be quoted as a backtest;
//   4. gross blended into net hides whether an edge died to cost (which is
//      what killed the one mechanism that found real signal).
//
// The fixture is GENERATED BY THE BACKEND (test/fixtures/…json, see its
// _provenance) rather than hand-written, because the last frontend card
// that guessed a backend field name rendered "qty undefined" in
// production.

const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const fixture = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures', 'forwardTestSnapshots.json'), 'utf8'));

// Lifted out of index.html rather than imported: there is no build step
// (CLAUDE.md), so the only way to test the shipped code is to run the
// shipped text.
function lift(name) {
  const start = html.indexOf('  function ' + name + '(');
  assert.notStrictEqual(start, -1, 'could not find function ' + name + ' in index.html');
  let depth = 0;
  const open = html.indexOf('{', start);
  for (let j = open; j < html.length; j++) {
    if (html[j] === '{') depth++;
    else if (html[j] === '}') { depth--; if (depth === 0) return html.slice(start, j + 1); }
  }
  throw new Error('unbalanced braces for ' + name);
}
function liftVar(name) {
  const start = html.indexOf('  var ' + name + ' = ');
  assert.notStrictEqual(start, -1, 'could not find var ' + name);
  const eq = html.indexOf('=', start);
  if (html.slice(eq + 1).trimStart()[0] === '{') {
    let depth = 0;
    const open = html.indexOf('{', eq);
    for (let j = open; j < html.length; j++) {
      if (html[j] === '{') depth++;
      else if (html[j] === '}') { depth--; if (depth === 0) return html.slice(start, j + 1) + ';'; }
    }
    throw new Error('unbalanced braces for ' + name);
  }
  return html.slice(start, html.indexOf(';', eq) + 1);
}

function build(snapshots) {
  const el = { innerHTML: '' };
  const src = `
    ${liftVar('FORWARD_TEST_STRATEGY_LABELS')}
    ${liftVar('FORWARD_TEST_STRATEGY_ORDER')}
    var forwardTestSnapshots = SNAPS;
    var document = { getElementById: function(id){ return id === 'forwardTestRecord' ? EL : null; } };
    ${lift('escapeHtml')}
    ${lift('ftMoney')}
    ${lift('ftPercent')}
    ${lift('ftNumber')}
    ${lift('forwardTestSupersededIds')}
    ${lift('forwardTestSortedSnapshots')}
    ${lift('ftMetric')}
    ${lift('ftExitMixLine')}
    ${lift('ftSeriesTable')}
    ${lift('ftStrategyBlock')}
    ${lift('renderForwardTestRecord')}
    renderForwardTestRecord();
  `;
  new Function('SNAPS', 'EL', src)(snapshots, el); // eslint-disable-line no-new-func
  return el.innerHTML;
}

const ALL = fixture.snapshots;
const [week0, week1, week1correction, week2] = ALL;

// Split the rendered page into one chunk per strategy block, so an
// assertion about "the crypto block" cannot be satisfied by text belonging
// to the ORB block above it.
function blocks(out) {
  const parts = out.split(/<div class="ft-strategy(?: refused)?">/);
  parts.shift();
  return parts;
}

function main() {
  // ---- 1. A REFUSED VERDICT RENDERS AS REFUSED.
  // Not as a blank, and not as a neutral-looking figure. The fixture's
  // week-1 ORB block has 3 closed trades against a gate of 20.
  {
    const out = build([week1]);
    const orb = blocks(out)[0];
    const block = week1.strategies['intraday-orb'];
    assert.strictEqual(block.verdictRefused, true, 'fixture precondition');

    // The verdict slot says so, in words.
    assert.ok(/Verdict refused/i.test(orb), 'a refused verdict must say it is refused');
    // The backend's own reason is printed, not paraphrased away.
    assert.ok(orb.indexOf(escapeForHtml(block.verdictRefusedReason)) !== -1,
      'verdictRefusedReason must be shown, so the reader knows WHY there is no verdict');
    assert.ok(/ft-strategy refused/.test(out), 'the whole block must carry the refused state, not one field');
    // And it must not be blank: the numbers ARE recorded, they are just
    // marked as unfit to judge on.
    assert.ok(/ft-metric provisional/.test(orb), 'a below-gate figure must be marked provisional, not hidden');
    assert.ok(orb.indexOf(block.cumulative.trades + ' of ' + block.minTradesForConfidence + ' trades') !== -1,
      'the sample size must travel with the figures, not sit in one banner');
    // The verdict slot itself must never be a bare number -- a numeric
    // verdict is the thing that gets screenshotted and quoted.
    const verdict = /<div class="ft-verdict[^"]*">([^<]*)<\/div>/.exec(orb);
    assert.ok(verdict, 'a verdict slot must render at all');
    assert.ok(!/^[\s$-]*[\d.]+%?\s*$/.test(verdict[1]), 'a refused verdict must never render as a number: ' + verdict[1]);

    // A sufficient sample is allowed to say so -- otherwise this gate
    // would pass on a page that refuses everything.
    const out2 = build([week2]);
    assert.strictEqual(week2.strategies['intraday-orb'].verdictRefused, false, 'fixture precondition');
    assert.ok(/Sample sufficient/.test(blocks(out2)[0]), 'a sufficient sample must not be reported as refused');
    console.log('A refused verdict renders as refused, never as a number or a blank: PASS');
  }

  // ---- 2. THE THREE STRATEGIES ARE NEVER POOLED.
  {
    const out = build([week2]);
    const bs = blocks(out);
    assert.strictEqual(bs.length, 3, 'exactly one block per strategy, no combined block');
    assert.ok(/Intraday ORB/.test(bs[0]) && /Equities fade/.test(bs[1]) && /Crypto/.test(bs[2]));
    assert.ok(!/(All strategies|Combined|Pooled|Total across|Overall)/i.test(out),
      'no combined figure may appear anywhere on the record');
    // The strongest form: no rendered money figure may equal the sum of the
    // three strategies' nets. That is the number that would look best.
    const nets = ['intraday-orb', 'equities-fade', 'crypto'].map((s) => week2.strategies[s].cumulative.netPnl);
    const pooled = nets.reduce((a, b) => a + b, 0);
    const shown = (out.match(/-?\$[\d,]+\.\d\d/g) || []).map((v) => Number(v.replace(/[$,]/g, '')));
    assert.ok(Math.abs(pooled) > 0.01, 'fixture precondition: a pooled figure would be distinguishable');
    assert.ok(!shown.some((v) => Math.abs(Math.abs(v) - Math.abs(pooled)) < 0.005),
      'a figure equal to the three strategies summed must never be rendered');
    console.log('Strategies are never pooled: PASS');
  }

  // ---- 3. THE WARNING AND THE MECHANISM STATUS ARE WHERE THE NUMBERS ARE.
  // Not behind a tooltip and not behind an expander -- a doc is not read
  // at the moment somebody is quoting a number.
  {
    const out = build([week2]);
    assert.ok(out.indexOf(escapeForHtml(week2.warning)) !== -1, 'the snapshot warning must be rendered in full');
    assert.ok(/2\.71/.test(out), 'the withdrawn figures the warning names must survive rendering');
    assert.ok(out.indexOf(week2.kind) !== -1 && /not a backtest/i.test(out));
    assert.ok(out.indexOf(week2.notQuotableAs) !== -1);
    // In the DOM, above the first figure -- not in a title= or a <details>.
    assert.ok(out.indexOf('ft-warning') < out.indexOf('ft-metric-value'), 'the warning must precede the figures');
    assert.ok(!/<details|title="[^"]*forward test/i.test(out), 'the warning may not be hidden behind a disclosure widget');
    // Each strategy carries its own research verdict next to its own P&L.
    blocks(out).forEach((b, i) => {
      const key = ['intraday-orb', 'equities-fade', 'crypto'][i];
      assert.ok(b.indexOf(escapeForHtml(week2.strategies[key].mechanismStatus)) !== -1,
        key + ' must show its mechanism status in the same block as its figures');
      assert.ok(b.indexOf('ft-mechanism') < b.indexOf('ft-metric-value'),
        key + "'s mechanism status must come before its numbers");
    });
    // The sample says what it is a sample OF.
    assert.ok(out.indexOf(week2.since.date) !== -1 && out.indexOf(escapeForHtml(week2.since.reason)) !== -1,
      'the since marker and its reason must be shown');
    console.log('The warning, mechanism status and since marker sit with the figures: PASS');
  }

  // ---- 4. GROSS, COST AND NET ARE THREE NUMBERS.
  // One blended figure hides whether an edge died to cost -- which is what
  // killed the one mechanism that found real signal.
  {
    const out = build([week2]);
    const orb = blocks(out)[0];
    const m = week2.strategies['intraday-orb'].cumulative;
    assert.ok(m.modeledCost > 0, 'fixture precondition');
    assert.ok(/Gross P&amp;L/.test(orb) && /Modeled cost/.test(orb) && /Net P&amp;L/.test(orb),
      'all three of gross, modeled cost and net must be labelled separately');
    [m.grossPnl, m.modeledCost, m.netPnl].forEach((v) => {
      assert.ok(orb.indexOf('$' + Math.abs(v).toFixed(2)) !== -1, 'missing figure ' + v);
    });
    assert.notStrictEqual(m.grossPnl.toFixed(2), m.netPnl.toFixed(2), 'fixture precondition');
    // The weekly series carries the same three columns, for the same reason.
    assert.ok(/<th>Gross<\/th><th>Modeled cost<\/th><th>Net<\/th>/.test(out),
      'the accumulating series must carry cost as its own column');
    console.log('Gross, modeled cost and net are shown separately: PASS');
  }

  // ---- 5. THE SERIES ACCUMULATES, AND A SUPERSEDED WEEK STAYS VISIBLE.
  // The value of the record is the trend, and a record that can quietly
  // drop the week it did not like is not evidence.
  {
    const out = build(ALL);
    assert.ok(out.indexOf(week1.periodKey) !== -1 && out.indexOf(week2.periodKey) !== -1,
      'every week must appear in the series, not just the latest');
    assert.ok(/tr class="superseded"/.test(out), 'a superseded week must still be rendered');
    assert.ok(/superseded by/.test(out), 'and must say what replaced it');
    assert.strictEqual(week1correction.supersedes, week1.id, 'fixture precondition');
    // The headline figures come from the standing snapshot, not the one it
    // corrected -- otherwise the page reports a number the record retracted.
    const orb = blocks(out)[0];
    const standing = week2.strategies['intraday-orb'].cumulative;
    assert.ok(orb.indexOf('$' + Math.abs(standing.netPnl).toFixed(2)) !== -1,
      'the standing snapshot supplies the headline figures');
    console.log('The weekly series accumulates and a superseded week stays visible: PASS');
  }

  // ---- 6. NOTHING HERE REACHES FOR THE SECRET-PROTECTED ENDPOINT.
  // GET /forward-test is behind PROXY_SHARED_SECRET; a secret in a static
  // page is a published secret.
  {
    assert.ok(!/\/forward-test['"?]/.test(html), 'the frontend must never call GET /forward-test');
    assert.ok(/forwardTestSnapshots: Array\.isArray\(data\.forwardTestSnapshots\)/.test(html),
      'the record must arrive on the existing user-doc listener');
    console.log('The record is read from the user doc, never from the secret-protected endpoint: PASS');
  }

  // ---- 7. NO FIGURE IS INVENTED WHERE THE BACKEND EMITTED NONE.
  // A profit factor with no losing trade has a missing denominator, not an
  // infinite value, and "undefined"/"NaN"/"Infinity" on the page is the
  // qty-undefined bug again.
  {
    const out = build(ALL);
    assert.ok(!/undefined|NaN|Infinity|null/.test(out), 'no placeholder value may reach the page');
    assert.strictEqual(week0.strategies.crypto.cumulative.profitFactor, null, 'fixture precondition');
    assert.ok(/no denominator/.test(build([week0])), 'an absent profit factor must say why it is absent');
    console.log('An absent backend value never renders as a fabricated one: PASS');
  }

  console.log('\nAll forward-test record gates passed.');
}

function escapeForHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

main();
